name: gmdsitut
channels:
  - conda-forge
  - nodefaults
dependencies:
  - python=3.11
  - pip
  - pandas>=2.0,<3.0
  - numpy<2 
  - matplotlib 
  - openpyxl
  - xlrd
  - jupyter
  - notebook
  - scipy
  - shapely
  - rtree
  - pyproj>=2.0
  - pyshp
  - psutil
  - git
  - nbconvert
  - modflow-devtools
  - scikit-learn
  - pip:
       - -e ./dependencies/flopy
       - -e ./dependencies/pyemu
       - pypestutils
