remote_theme: "mmistakes/minimal-mistakes@4.24.0"

minimal_mistakes_skin    : "contrast" # "air", "aqua", "contrast", "dark", "dirt", "neon", "mint", "plum", "sunrise"


plugins:
  - jekyll-include-cache
