
remote_theme: gmdsi/just-the-docs
#logo: "banner_pyemu_clean.png"
title: GMDSI Notebooks
description: Tutorial Notebooks for Decision-Support Groundwater Modelling
baseurl: "/GMDSI_notebooks" # the subpath of your site, e.g. /blog
url: "https://gmdsi.github.io" # the base hostname & protocol for your site, e.g. http://example.com
#markdown: CommonMarkGhPages #kramdown 
