name: nbs continuous integration

on: 
  #schedule:
  #  - cron: '0 8 * * *' # run at 8 AM UTC (12 am PST)
  push:
  #pull_request:    
    branches:    
      - dev

jobs:
  nbCI:
    name: tests
    runs-on: ${{ matrix.os }}
    timeout-minutes: 120
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest , macos-latest] 
        python-version: [3.9] # [3.7, 3.8, 3.7, 3.6]
        run-type: [std]
        test-path: [
              "nb_tests.py", 
            ]

   steps:
      - uses: actions/checkout@v2
      - uses: conda-incubator/setup-miniconda@v2
        with:
          activate-environment: gmdsitut
          environment-file: environment.yml
          python-version: 3.9
          auto-activate-base: false
      - shell: bash -l {0}
        run: |
          conda info
          conda list
      - name: run test nbs
        shell: bash -l {0}
        run: |
            python -m ./tests/nb_tests.py