# ripped from pyemu repo
name: repo ci

on: 
  #schedule:
  #  - cron: '0 8 * * *' # run at 8 AM UTC (12 am PST)
  pull_request:  
    branches:    
      - main

jobs:
  pyemuCI:
    name: autotests
    runs-on: ${{ matrix.os }}
    timeout-minutes: 120
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest] # , macos-latest] 
        python-version: [3.9] # , 3.7, 3.6]
        run-type: [std]
        test-path: [
              "nb_tests.py"
                    ]

    steps:
    - uses:  actions/checkout@v2 # checksout this repo
    # - name: Setup Ninja
      # if: ${{ runner.os == 'Windows' }} 
    - uses: seanmiddleditch/gha-setup-ninja@master

    - name: Cache Miniconda
      uses: actions/cache@v2
      env:
        # Increase this value to reset cache if etc/environment.yml has not changed
        CACHE_NUMBER: 0
      with:
        path: ~/conda_pkgs_dir
        key: ${{ runner.os }}-${{ matrix.python-version }}-${{ matrix.run-type }}-${{ env.CACHE_NUMBER }}-${{ hashFiles('./environment.yml') }}
    
    - name: Set Windows ENV
      if: runner.os == 'Windows'
      uses: ilammy/msvc-dev-cmd@v1

    # Standard python fails on windows without GDAL installation
    # Using custom bash shell ("shell: bash -l {0}") with Miniconda
    - name: Setup Miniconda
      uses: conda-incubator/setup-miniconda@v2
      with:
        miniforge-version: latest
        # miniconda-version: "latest"
        python-version: ${{ matrix.python-version }}
        # mamba-version: "*"
        # channels: conda-forge
        miniforge-variant: Mambaforge
        # auto-update-conda: true
        activate-environment: gmdsitut
        use-mamba: true
        # environment-file: etc/environment.yml
        # use-only-tar-bz2: true

    - name: Add packages to pyemu environment using conda
      if: ${{ matrix.python-version < 3.8 }}
      # if: ${{ runner.os == 'Windows' || matrix.python-version < 3.8 }}
      shell: bash -l {0}
      run: |
          conda env update --name gmdsitut --file ./environment.yml
    
    - name: Add packages to pyemu environment using mamba
      # if: ${{ runner.os != 'Windows' && matrix.python-version >= 3.8 }}
      if: ${{ matrix.python-version >= 3.8 }}
      shell: bash -l {0}
      run: |
          mamba env update --name gmdsitut --file ./environment.yml
    

    - name: ${{ matrix.test-path }}
      shell: bash -l {0}
      run: |
        python ./autotest/${{ matrix.test-path }}


    - name: Coveralls
      if: ${{ runner.os == 'Linux' && matrix.python-version > 3.6 }}
      uses: AndreMiras/coveralls-python-action@develop
      with:
        parallel: true
        debug: false
        flag-name: ${{ matrix.python-version }}-${{ matrix.test-path }}


  coveralls_finish:
    needs: pyemuCI
    runs-on: ubuntu-latest
    steps:
    - name: Coveralls Finished
      uses: AndreMiras/coveralls-python-action@develop
      with:
        parallel-finished: true
        debug: true

