# ripped from pyemu repo
name: repo ci

on:
  schedule:
    - cron: '0 8 1 * *'  # 1st of each month at 8 AM UTC
  pull_request:
    branches:
      - "**"

env:
  CACHE_NUMBER: 0  # increase to reset cache manually

jobs:
  build:

    strategy:
      fail-fast: false
      matrix:
        os: ["windows-latest", "ubuntu-latest", "macos-latest"]
        python-version: ["3.11"]
        test-path: [
              "nb_tests_part0.py",
              "nb_tests_part1.py",
              "nb_tests_part2.py"
                  ]

    name: ${{ matrix.os }}-${{ matrix.test-path }}
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4

      - name: Install Conda environment using micromamba
        uses: mamba-org/setup-micromamba@v1
        with:
            environment-file: environment.yml
            environment-name: gmdsitut
            create-args: >-
              python=${{ matrix.python-version }}
            cache-downloads: true
            cache-environment: true
            cache-environment-key: environment-${{ steps.date.outputs.date }}
            cache-downloads-key: downloads-${{ steps.date.outputs.date }}

      # run .py that calls nb's
      - name: Run tests
        shell: bash -l {0}
        run: python ./autotest/${{ matrix.test-path }}
